# Specify version format
version: "{build}-{branch}"

# Build worker image (VM template)
image: Visual Studio 2015

# build platform, i.e. Win32, x64.
platform:
  - x64

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - echo Vulkan Version %VULKAN_SDK_VERSION%
  - cmake --version
  - msbuild /version

environment:
  PYTHON: "C:\\Python36"

# clone directory
clone_folder: C:\projects\engine

# branches to build
branches:
  except:
    - gh-pages
    - tmp

# scripts that run after cloning repository
install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - git submodule update --init --recursive
  - python.exe scripts\download_vulkan.py .
  - start /wait vulkan_sdk.exe /S

# scripts to run before build
before_build:
  - cd C:\projects\engine
  - if "%PLATFORM%"=="Win32" set CMAKE_GENERATOR_PLATFORM=""
  - if "%PLATFORM%"=="x64"   set CMAKE_GENERATOR_PLATFORM="x64"
  - python.exe generate.py --name Engine --package me.edoren.engine --platform windows --build-type %CONFIGURATION% --cmake-args CMAKE_GENERATOR_PLATFORM=%CMAKE_GENERATOR_PLATFORM%
  - cd build\windows

build_script:
  - python.exe build.py

test: on

test_script:
  - cd C:\projects\engine\build\windows\tests
  - ctest -V -C %CONFIGURATION%
