variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  # Temporal fix for SSL certificate error in GitLab CI see
  # https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2148
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build

linux_gcc:
  stage: build
  image: gcc:6
  tags:
    - docker
  before_script:
    - apt-get update -qq
    - apt-get install -qq cmake libsdl2-dev libglew-dev
    - export CC=gcc
    - export CXX=g++
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DENGINE_BUILD_STATIC=OFF
    - make
