############################################################
## Environment Variables
############################################################

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  # Temporal fix for SSL certificate error in GitLab CI see
  # https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2148
  GIT_SSL_NO_VERIFY: "true"


############################################################
## Platform Configuration
############################################################

.linux_config:
  image: ubuntu:16.04
  tags:
    - docker
  before_script:
    # System configuration
    - apt-get update -qq
    - apt-get install -qq python3 software-properties-common  # install add-apt-repository
    - add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - apt-get update -qq
    # Engine dependencies
    - apt-get install -qq build-essential clang gcc-6 g++-6 cmake libsdl2-dev libglew-dev
    # SDL2 dependencies
    - apt-get install -qq libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev
    # Install the VulkanSDK
    - python3 scripts/download_vulkan.py $PWD
    - export VULKAN_SDK=$PWD/VulkanSDK/x86_64
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$VULKAN_SDK/lib"
    - export VK_LAYER_PATH="$VULKAN_SDK/etc/explicit_layer.d"
    - export PATH="$PATH:$VULKAN_SDK/bin"
  only:
    - master
    - web
  except:
    - gh-pages

.android_config:
  image: lakoo/android-ndk:25-26.0.2-r15c
  tags:
    - docker
  before_script:
    # Accept all the Android SDK licenses
    - (for i in {0..100}; do echo y; done) | sdkmanager --licenses
    # System configuration
    - apt-get update -qq
    - apt-get install -qq cmake build-essential gcc g++ python3
    # Install glslang
    - git clone https://github.com/KhronosGroup/glslang.git --depth 1
    - mkdir -p glslang/build
    - cd glslang/build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release --target install
    - cd -
  only:
    - master
    - web
  except:
    - gh-pages

stages:
  - build
  - test


############################################################
## Build Tasks
############################################################

build:linux_gcc:
  extends: .linux_config
  stage: build
  variables:
    CC: gcc-6
    CXX: g++-6
  script:
    - ./generate.py --name Engine --platform linux --package me.edoren.engine --build-type Release
    - cd build/linux
    - ./build.py
  artifacts:
    expire_in: 1 day
    paths:
      - build/linux/

build:linux_clang:
  extends: .linux_config
  stage: build
  variables:
    CC: clang
    CXX: clang++
  script:
    - ./generate.py --name Engine --platform linux --package me.edoren.engine --build-type Release
    - cd build/linux
    - ./build.py
  artifacts:
    expire_in: 1 day
    paths:
      - build/linux/

build:android:
  extends: .android_config
  stage: build
  script:
    - ./generate.py --name Engine --platform android --package me.edoren.engine --build-type Release
    - cd build/android
    - ./build.py
  artifacts:
    expire_in: 1 day
    paths:
      - build/android/


############################################################
## Test Tasks
############################################################

test:linux_gcc:
  extends: .linux_config
  stage: test
  script:
    - cd build/linux/tests/
    - ctest -V
  dependencies:
    - build:linux_gcc

test:linux_clang:
  extends: .linux_config
  stage: test
  script:
    - cd build/linux/tests/
    - ctest -V
  dependencies:
    - build:linux_clang
