if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(OS_WINDOWS 1)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(OS_MACOS 1)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(OS_LINUX 1)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
    set(OS_ANDROID 1)
else()
    message(FATAL_ERROR "Unsupported operating system ${CMAKE_SYSTEM_NAME}.")
endif()

if(MSVC)
    set(COMPILER_MSVC 1)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "^(Apple)?Clang$")
    set(COMPILER_CLANG 1)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(COMPILER_GCC 1)
else()
    message(FATAL_ERROR "Unsupported compiler.")
endif()

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(COMPILER_ARCH 64)
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(COMPILER_ARCH 32)
else()
    message(FATAL_ERROR "Unsupported compiler architecture.")
endif()
